name: Lint OpenAPI

on:
  push:
    paths:
      - 'packages/contracts/openapi.yaml'
  pull_request:
    paths:
      - 'packages/contracts/openapi.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate OpenAPI
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: packages/contracts/openapi.yaml

