name: Lint OpenAPI

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/contracts/openapi.yaml'
  pull_request:
    paths:
      - 'packages/contracts/openapi.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Lint with Spectral CLI
        run: npx -y @stoplight/spectral-cli@6 lint packages/contracts/openapi.yaml --ruleset spectral:oas --fail-severity=error
